# Generated by Django 4.2.1 on 2023-06-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchesModel',
            fields=[
                ('search_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('consult', models.TextField(verbose_name='Consulta')),
                ('totals_consults', models.IntegerField(default=0, verbose_name='Cantidad de Búsquedas Totales')),
                ('first_search', models.DateTimeField(auto_now_add=True, verbose_name='Primera Búsqueda')),
                ('last_search', models.DateTimeField(auto_now=True, verbose_name='Ultima Búsqueda')),
                ('last_number_results', models.IntegerField(default=0, verbose_name='Ultima Búsqueda')),
            ],
        ),
    ]
